# Generated by Django 3.2.2 on 2021-05-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_cours_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
